server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stefantflcdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: debug
domain:
  url: http://localhost:8090
rethinkdb:
  url: 127.0.0.1
  user: admin
  pass: admin