spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
domain:
  url: https://www.stefantflc.me
rethinkdb:
  url: ${RETHINKDB_URL}
  user: ${RETHINK_USER}
  pass: ${RETHINK_PASS}
mail:
  pass : ${APP_MAIL_PASS}
jwt:
  secret: ${JWT_SECRET}
dropbox:
  token: ${DROPBOX_TOKEN}
  env: ${DROPBOX_ENV}